name: Example
options:
  minimumXcodeGenVersion: 2.2.0
  bundleIdPrefix: jp.toshi0383
  deploymentTarget: [iOS: "9.0"]
settings:
  SWIFT_VERSION: 4.2
configFiles:
  Debug: user.xcconfig
  Release: user.xcconfig
targets:
  Example:
    platform: iOS
    type: application
    sources:
      - Example/
      - Exclude/
    dependencies:
      - carthage: RxCocoa
      - carthage: RxSwift
      - target: VideoPlayer
  VideoPlayer:
    platform: iOS
    type: framework
    sources:
      - Sources/
    dependencies:
      - carthage: RxCocoa
      - carthage: RxSwift
  VideoPlayerTests:
    platform: iOS
    type: bundle.unit-test
    settings:
      SWIFT_OBJC_BRIDGING_HEADER: Tests/VideoPlayerTests/BridgingHeader.h
    sources:
      - path: Tests/VideoPlayerTests/
        name: VideoPlayerTests
        excludes:
        - "XCTestManifests.swift"
    dependencies:
      - target: VideoPlayer
      - carthage: RxCocoa
      - carthage: RxSwift
      - carthage: RxTest
    scheme:
      testTargets:
        - VideoPlayerTests
      gatherCoverageData: true
